# This workflow will run tests using node and then publish a package to npm registry when a tag is pushed
# For more information see: https://github.com/actions/starter-workflows/blob/main/ci/npm-publish.yml
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: publish to npm

on:
  push:
    tags:
      - v*

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: echo ${{secrets.NPM_CONFIG_NAME}}
      - run: yarn
      - run: yarn run lint
      - run: yarn run test

  publish-npm:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: yarn run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
